// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Card Contato documents
 */
interface CardContatoDocumentData {
  /**
   * Icone Card field in *Card Contato*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_contato.icone_card
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone_card: prismic.ImageField<never>;

  /**
   * Titulo Card field in *Card Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_contato.titulo_card
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_card: prismic.KeyTextField;

  /**
   * Subtitulo Card field in *Card Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_contato.subtitulo_card
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo_card: prismic.KeyTextField;

  /**
   * Url Card field in *Card Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_contato.url_card
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url_card: prismic.KeyTextField;
}

/**
 * Card Contato document from Prismic
 *
 * - **API ID**: `card_contato`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardContatoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CardContatoDocumentData>,
    "card_contato",
    Lang
  >;

/**
 * Content for Card DIferenciais Revendedor documents
 */
interface CardDiferenciaisRevendedorDocumentData {
  /**
   * Icone Imagem field in *Card DIferenciais Revendedor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card_diferenciais_revendedor.icone_imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone_imagem: prismic.ImageField<never>;

  /**
   * Titulo Card Diferenciais field in *Card DIferenciais Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_diferenciais_revendedor.titulo_card_diferenciais
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_card_diferenciais: prismic.KeyTextField;

  /**
   * Subtitulo Card Diferenciais field in *Card DIferenciais Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: card_diferenciais_revendedor.subtitulo_card_diferenciais
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo_card_diferenciais: prismic.KeyTextField;
}

/**
 * Card DIferenciais Revendedor document from Prismic
 *
 * - **API ID**: `card_diferenciais_revendedor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CardDiferenciaisRevendedorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CardDiferenciaisRevendedorDocumentData>,
    "card_diferenciais_revendedor",
    Lang
  >;

type ContatoDocumentDataSlicesSlice = never;

/**
 * Content for Contato documents
 */
interface ContatoDocumentData {
  /**
   * Slice Zone field in *Contato*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContatoDocumentDataSlicesSlice> /**
   * Meta Title field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contato.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contato.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contato*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Keywords field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.meta_keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Og Title field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.meta_og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_title: prismic.KeyTextField;

  /**
   * Meta Og URL field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.meta_og_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_url: prismic.KeyTextField;

  /**
   * Meta OG Site Name field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.meta_og_site_name
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_site_name: prismic.KeyTextField;

  /**
   * Meta Og Description field in *Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contato.meta_og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_description: prismic.KeyTextField;
}

/**
 * Contato document from Prismic
 *
 * - **API ID**: `contato`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContatoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContatoDocumentData>,
    "contato",
    Lang
  >;

type HomeDocumentDataSlicesSlice = never;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Titulo Slide field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titulo_slide
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_slide: prismic.KeyTextField;

  /**
   * Subtitulo Slide field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.subtitulo_slide
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo_slide: prismic.KeyTextField;

  /**
   * Nome Botao field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.nome_botao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_botao: prismic.KeyTextField;

  /**
   * Url Botao field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.url_botao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url_botao: prismic.KeyTextField;

  /**
   * Titulo Listagem Produtos field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titulo_listagem_produtos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_listagem_produtos: prismic.KeyTextField;

  /**
   * Subtitulo Listagem Produtos field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.subtitulo_listagem_produtos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo_listagem_produtos: prismic.KeyTextField;

  /**
   * imagem_slide1 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.imagem_slide1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_slide1: prismic.ImageField<never>;

  /**
   * imagem_slide2 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.imagem_slide2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_slide2: prismic.ImageField<never>;

  /**
   * imagem_slide3 field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.imagem_slide3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_slide3: prismic.ImageField<never>;

  /**
   * Imagem CTA field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.imagem_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_cta: prismic.ImageField<never>;

  /**
   * Titulo Seção CTA Revendedor field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titulo_secao_cta_revendedor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_secao_cta_revendedor: prismic.KeyTextField;

  /**
   * Titulo Pagina field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titulo_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_pagina: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Keywords field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Adicione o contéudo entre " "
   * - **API ID Path**: home.meta_keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Og Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_title: prismic.KeyTextField;

  /**
   * Meta Og URL field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_og_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_url: prismic.KeyTextField;

  /**
   * Meta OG Site Name field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_og_site_name
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_site_name: prismic.KeyTextField;

  /**
   * Meta Og Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_description: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Perguntas Frequentes documents
 */
interface PerguntasFrequentesDocumentData {
  /**
   * Pergunta field in *Perguntas Frequentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perguntas_frequentes.pergunta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pergunta: prismic.KeyTextField;

  /**
   * Resposta field in *Perguntas Frequentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perguntas_frequentes.resposta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta: prismic.KeyTextField;
}

/**
 * Perguntas Frequentes document from Prismic
 *
 * - **API ID**: `perguntas_frequentes`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PerguntasFrequentesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PerguntasFrequentesDocumentData>,
    "perguntas_frequentes",
    Lang
  >;

/**
 * Content for Produto documents
 */
interface ProdutoDocumentData {
  /**
   * Slug field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.slug
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slug: prismic.KeyTextField;

  /**
   * Nome do Produto field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.nome_do_produto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_do_produto: prismic.KeyTextField;

  /**
   * Descricão do Produto field in *Produto*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_do_produto
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao_do_produto: prismic.RichTextField;

  /**
   * Imagem Galeria 1 field in *Produto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.imagem_galeria_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_galeria_1: prismic.ImageField<never>;

  /**
   * Imagem Galeria 2  field in *Produto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.imagem_galeria_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_galeria_2: prismic.ImageField<never>;

  /**
   * Imagem Galeria 3 field in *Produto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.imagem_galeria_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_galeria_3: prismic.ImageField<never>;

  /**
   * Imagem Galeria 4 field in *Produto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.imagem_galeria_4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_galeria_4: prismic.ImageField<never>;

  /**
   * Imagem Galeria 5 field in *Produto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.imagem_galeria_5
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_galeria_5: prismic.ImageField<never>;

  /**
   * Link Contato field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.link_contato
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_contato: prismic.KeyTextField /**
   * TItulo Especificação 1 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.titulo_especificacao_1
   * - **Tab**: Especificação 1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  titulo_especificacao_1: prismic.KeyTextField;

  /**
   * Descrição Especificação 1 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_1
   * - **Tab**: Especificação 1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_1: prismic.KeyTextField;

  /**
   * Descrição Especificação 2 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_2
   * - **Tab**: Especificação 1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_2: prismic.KeyTextField;

  /**
   * Descrição Especificação 3 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_3
   * - **Tab**: Especificação 1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_3: prismic.KeyTextField /**
   * TItulo Especificação 2 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.titulo_especificacao_2
   * - **Tab**: Especificação 2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  titulo_especificacao_2: prismic.KeyTextField;

  /**
   * Descrição Especificação 2_1 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_2_1
   * - **Tab**: Especificação 2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_2_1: prismic.KeyTextField;

  /**
   * Descrição Especificação 2_2 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_2_2
   * - **Tab**: Especificação 2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_2_2: prismic.KeyTextField;

  /**
   * Descrição Especificação 2_3 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_2_3
   * - **Tab**: Especificação 2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_2_3: prismic.KeyTextField /**
   * TItulo Especificação 3 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.titulo_especificacao_3
   * - **Tab**: Especificação 3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  titulo_especificacao_3: prismic.KeyTextField;

  /**
   * Descrição Especificação 3_1 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_3_1
   * - **Tab**: Especificação 3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_3_1: prismic.KeyTextField;

  /**
   * Descrição Especificação 3_2 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_3_2
   * - **Tab**: Especificação 3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_3_2: prismic.KeyTextField;

  /**
   * Descrição Especificação 3_3 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_3_3
   * - **Tab**: Especificação 3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_3_3: prismic.KeyTextField /**
   * TItulo Especificação 4 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.titulo_especificacao_4
   * - **Tab**: Especificação 4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  titulo_especificacao_4: prismic.KeyTextField;

  /**
   * Descrição Especificação 4_1 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_4_1
   * - **Tab**: Especificação 4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_4_1: prismic.KeyTextField;

  /**
   * Descrição Especificação 4_2 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_4_2
   * - **Tab**: Especificação 4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_4_2: prismic.KeyTextField;

  /**
   * Descrição Especificação 4_3 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_4_3
   * - **Tab**: Especificação 4
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_4_3: prismic.KeyTextField /**
   * TItulo Especificação 5 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.titulo_especificacao_5
   * - **Tab**: Especificação 5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  titulo_especificacao_5: prismic.KeyTextField;

  /**
   * Descrição Especificação 5_1 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_5_1
   * - **Tab**: Especificação 5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_5_1: prismic.KeyTextField;

  /**
   * Descrição Especificação 5_2 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_5_2
   * - **Tab**: Especificação 5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_5_2: prismic.KeyTextField;

  /**
   * Descrição Especificação 5_3 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_5_3
   * - **Tab**: Especificação 5
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_5_3: prismic.KeyTextField /**
   * TItulo Especificação 6 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.titulo_especificacao_6
   * - **Tab**: Especificação 6
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  titulo_especificacao_6: prismic.KeyTextField;

  /**
   * Descrição Especificação 6_1 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_6_1
   * - **Tab**: Especificação 6
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_6_1: prismic.KeyTextField;

  /**
   * Descrição Especificação 6_2 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_6_2
   * - **Tab**: Especificação 6
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_6_2: prismic.KeyTextField;

  /**
   * Descrição Especificação 6_3 field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.descricao_especificacao_6_3
   * - **Tab**: Especificação 6
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_especificacao_6_3: prismic.KeyTextField /**
   * Imagem Tamanho Camas field in *Produto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.imagem_tamanho_camas
   * - **Tab**: Imagem Tamanho de Cama
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  imagem_tamanho_camas: prismic.ImageField<never> /**
   * Meta_Title field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Keywords field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.meta_keywords
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Image field in *Produto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Description field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.meta_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Og Title field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.meta_og_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_title: prismic.KeyTextField;

  /**
   * Meta Og URL field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.meta_og_url
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_url: prismic.KeyTextField;

  /**
   * Meta OG Site Name field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.meta_og_site_name
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_site_name: prismic.KeyTextField;

  /**
   * Meta Og Description field in *Produto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produto.meta_og_description
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_description: prismic.KeyTextField;
}

/**
 * Produto document from Prismic
 *
 * - **API ID**: `produto`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProdutoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProdutoDocumentData>,
    "produto",
    Lang
  >;

type ProdutosDocumentDataSlicesSlice = never;

/**
 * Content for Produtos documents
 */
interface ProdutosDocumentData {
  /**
   * Slice Zone field in *Produtos*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: produtos.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProdutosDocumentDataSlicesSlice> /**
   * Meta Title field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: produtos.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: produtos.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Produtos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: produtos.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Keywords field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produtos.meta_keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Og Title field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produtos.meta_og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_title: prismic.KeyTextField;

  /**
   * Meta Og URL field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produtos.meta_og_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_url: prismic.KeyTextField;

  /**
   * Meta OG Site Name field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produtos.meta_og_site_name
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_site_name: prismic.KeyTextField;

  /**
   * Meta Og Description field in *Produtos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: produtos.meta_og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_description: prismic.KeyTextField;
}

/**
 * Produtos document from Prismic
 *
 * - **API ID**: `produtos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProdutosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProdutosDocumentData>,
    "produtos",
    Lang
  >;

type RevendedorDocumentDataSlicesSlice = never;

/**
 * Content for Revendedor documents
 */
interface RevendedorDocumentData {
  /**
   * Titulo Diferenciais field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.titulo_diferenciais
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_diferenciais: prismic.KeyTextField;

  /**
   * Titulo Formulário field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.titulo_formulario
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_formulario: prismic.KeyTextField;

  /**
   * Imagem Formulário field in *Revendedor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.imagem_formulario
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_formulario: prismic.ImageField<never>;

  /**
   * Titulo Imagem Formulário field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.titulo_imagem_formulario
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_imagem_formulario: prismic.KeyTextField;

  /**
   * Subtitulo Imagem Formulário field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.subtitulo_imagem_formulario
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo_imagem_formulario: prismic.KeyTextField;

  /**
   * Titulo FAQ Perguntas field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.titulo_faq_perguntas
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_faq_perguntas: prismic.KeyTextField;

  /**
   * Titulo Pagina field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.titulo_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_pagina: prismic.KeyTextField;

  /**
   * Slice Zone field in *Revendedor*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<RevendedorDocumentDataSlicesSlice> /**
   * Meta Title field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: revendedor.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: revendedor.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Revendedor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Keywords field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.meta_keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Og Title field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.meta_og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_title: prismic.KeyTextField;

  /**
   * Meta Og URL field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.meta_og_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_url: prismic.KeyTextField;

  /**
   * Meta OG Site Name field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.meta_og_site_name
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_site_name: prismic.KeyTextField;

  /**
   * Meta Og Description field in *Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: revendedor.meta_og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_description: prismic.KeyTextField;
}

/**
 * Revendedor document from Prismic
 *
 * - **API ID**: `revendedor`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RevendedorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RevendedorDocumentData>,
    "revendedor",
    Lang
  >;

/**
 * Content for Rodapé documents
 */
interface RodapeDocumentData {
  /**
   * Logo field in *Rodapé*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Descrição field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * Rua field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.rua
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  rua: prismic.KeyTextField;

  /**
   * Cep field in *Rodapé*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.cep
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  cep: prismic.NumberField;

  /**
   * Cidade field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.cidade
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cidade: prismic.KeyTextField;

  /**
   * Horário Seg a Quinta field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Especifique o horário de funcionamento dia de segunda a quinta feira
   * - **API ID Path**: rodape.horario_seg_quinta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  horario_seg_quinta: prismic.KeyTextField;

  /**
   * Horário SextaFeira field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Especifique o horário de funcionamento dia de sexta-feira
   * - **API ID Path**: rodape.horario_sextafeira
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  horario_sextafeira: prismic.KeyTextField;

  /**
   * Email field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Contato Telefônico field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.contato_telefonico
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contato_telefonico: prismic.KeyTextField;

  /**
   * Link Tel Whats field in *Rodapé*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.link_tel_whats
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_tel_whats: prismic.KeyTextField;
}

/**
 * Rodapé document from Prismic
 *
 * - **API ID**: `rodape`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RodapeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RodapeDocumentData>,
    "rodape",
    Lang
  >;

/**
 * Content for Seção Contato Duvidas documents
 */
interface SecaoContatoDuvidasDocumentData {
  /**
   * Titulo da Seção  field in *Seção Contato Duvidas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_contato_duvidas.titulo_da_secao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_da_secao: prismic.KeyTextField;

  /**
   * Subtitulo da Seção field in *Seção Contato Duvidas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_contato_duvidas.subtitulo_da_secao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo_da_secao: prismic.KeyTextField;

  /**
   * Link Contato field in *Seção Contato Duvidas*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_contato_duvidas.link_contato
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_contato: prismic.KeyTextField;
}

/**
 * Seção Contato Duvidas document from Prismic
 *
 * - **API ID**: `secao_contato_duvidas`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SecaoContatoDuvidasDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SecaoContatoDuvidasDocumentData>,
    "secao_contato_duvidas",
    Lang
  >;

/**
 * Content for Seção CTA Revendedor documents
 */
interface SecaoCtaRevendedorDocumentData {
  /**
   * icone_cta_revendedor field in *Seção CTA Revendedor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_cta_revendedor.icone_cta_revendedor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone_cta_revendedor: prismic.ImageField<never>;

  /**
   * Titulo Seção CTA Revendedor field in *Seção CTA Revendedor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: secao_cta_revendedor.titulo_secao_cta_revendedor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_secao_cta_revendedor: prismic.KeyTextField;
}

/**
 * Seção CTA Revendedor document from Prismic
 *
 * - **API ID**: `secao_cta_revendedor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SecaoCtaRevendedorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SecaoCtaRevendedorDocumentData>,
    "secao_cta_revendedor",
    Lang
  >;

type SobreDocumentDataSlicesSlice = never;

/**
 * Content for Sobre documents
 */
interface SobreDocumentData {
  /**
   * Titulo  field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Campo_Texto_1 field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.campo_texto_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  campo_texto_1: prismic.KeyTextField;

  /**
   * Campo_Texto_2 field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.campo_texto_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  campo_texto_2: prismic.KeyTextField;

  /**
   * Campo_Texto_3 field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.campo_texto_3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  campo_texto_3: prismic.KeyTextField;

  /**
   * Campo_Texto_4 field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.campo_texto_4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  campo_texto_4: prismic.KeyTextField;

  /**
   * Imagem_Empresa field in *Sobre*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.imagem_empresa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_empresa: prismic.ImageField<never>;

  /**
   * Titulo Página field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.titulo_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_pagina: prismic.KeyTextField;

  /**
   * Slice Zone field in *Sobre*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SobreDocumentDataSlicesSlice> /**
   * Meta Title field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: sobre.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: sobre.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Sobre*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Keywords field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.meta_keywords
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Meta Og Title field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.meta_og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_title: prismic.KeyTextField;

  /**
   * Meta Og URL field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.meta_og_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_url: prismic.KeyTextField;

  /**
   * Meta OG Site Name field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.meta_og_site_name
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_site_name: prismic.KeyTextField;

  /**
   * Meta Og Description field in *Sobre*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre.meta_og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_og_description: prismic.KeyTextField;
}

/**
 * Sobre document from Prismic
 *
 * - **API ID**: `sobre`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SobreDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<SobreDocumentData>, "sobre", Lang>;

/**
 * Content for Titulo Pagina Contato documents
 */
interface TituloPaginaContatoDocumentData {
  /**
   * TItulo Pagina field in *Titulo Pagina Contato*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: titulo_pagina_contato.titulo_pagina
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_pagina: prismic.KeyTextField;
}

/**
 * Titulo Pagina Contato document from Prismic
 *
 * - **API ID**: `titulo_pagina_contato`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TituloPaginaContatoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TituloPaginaContatoDocumentData>,
    "titulo_pagina_contato",
    Lang
  >;

export type AllDocumentTypes =
  | CardContatoDocument
  | CardDiferenciaisRevendedorDocument
  | ContatoDocument
  | HomeDocument
  | PerguntasFrequentesDocument
  | ProdutoDocument
  | ProdutosDocument
  | RevendedorDocument
  | RodapeDocument
  | SecaoContatoDuvidasDocument
  | SecaoCtaRevendedorDocument
  | SobreDocument
  | TituloPaginaContatoDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      CardContatoDocument,
      CardContatoDocumentData,
      CardDiferenciaisRevendedorDocument,
      CardDiferenciaisRevendedorDocumentData,
      ContatoDocument,
      ContatoDocumentData,
      ContatoDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PerguntasFrequentesDocument,
      PerguntasFrequentesDocumentData,
      ProdutoDocument,
      ProdutoDocumentData,
      ProdutosDocument,
      ProdutosDocumentData,
      ProdutosDocumentDataSlicesSlice,
      RevendedorDocument,
      RevendedorDocumentData,
      RevendedorDocumentDataSlicesSlice,
      RodapeDocument,
      RodapeDocumentData,
      SecaoContatoDuvidasDocument,
      SecaoContatoDuvidasDocumentData,
      SecaoCtaRevendedorDocument,
      SecaoCtaRevendedorDocumentData,
      SobreDocument,
      SobreDocumentData,
      SobreDocumentDataSlicesSlice,
      TituloPaginaContatoDocument,
      TituloPaginaContatoDocumentData,
      AllDocumentTypes,
    };
  }
}
